version: "3.3"

services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    labels:
      - "traefik.http.routers.dashboard.service=api@internal"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  ssr:
    image: localhost:5000/belderkit/ssr
    container_name: ssr
    labels:
      - traefik.enable=true
      - traefik.http.routers.ssr.rule=(Host(`belderkit.localhost`))
      - traefik.http.routers.ssr.entrypoints=web
      - traefik.http.services.ssr.loadbalancer.server.port=3000

  db:
    container_name: postgres-database
    image: postgres:15.0-alpine
    environment:
      # TODO: Change on env variables from github secret
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: db
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.5"
        reservations:
          memory: 128M
