version: "3.3"

services:
  db:
    container_name: postgres-database
    image: postgres:15.0-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: db
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.5"
        reservations:
          memory: 128M
  pgadmin:
    container_name: pg-admin
    image: dpage/pgadmin4:6.21
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@example.com
      PGADMIN_DEFAULT_PASSWORD: qwe
